blueprint:
  name: Motion Light Timer
  description: |
    # Motion Light Timer

    Verlichting schakelen op basis van beweging. Deze Blueprint moet gebruikt worden i.c.m. de Motion Light Automation Blueprint. Deze automation zorgt ervoor dat er een timer gestart of gestopt wordt n.a.v. het inschakelen van de verlichting o.b.v. beweging.

    📕 Meer info en blueprints [hier](https://github.com/QLVR-IT/ha-blueprints).

    ℹ️ Versie 2025.01.05
  source_url: https://github.com/QLVR-IT/ha-blueprints/blob/main/motion_light_timer.yaml
  domain: automation
  homeassistant:
    min_version: 2024.1.0
  input:
    motion_sensor:
      name: Motion Sensor Occupancy
      description: Selecteer de bewegingsmelder(groep) welke gebruikt wordt.
      selector:
        entity:
          multiple: false
          filter:
          - integration: mqtt
            domain: binary_sensor
            device_class: motion
    target_light:
      name: Lights
      description: Selecteer welke lamp(en) geschakeld moeten worden
      selector:
        entity:
          multiple: true
          filter:
            - domain: light
    light_timer:
      name: Light Timer
      description: Selecteer welke timer gebruikt wordt om de verlichting weer uit
        te schakelen
      selector:
        entity:
          multiple: false
          filter:
          - domain: timer
    motion_enabled:
      name: Motion enabled
      description: Selecteer welke boolean gebruikt wordt om te bepalen of beweging
        aan of uit staat
      selector:
        entity:
          multiple: false
          filter:
          - domain: input_boolean
max_exceeded: silent
trace:
  stored_traces: 25
triggers:
- trigger: homeassistant
  event: start
- trigger: event
  event_type: automation_reloaded
- trigger: state
  entity_id: !input target_light
  to: 'off'
- trigger: state
  entity_id: !input motion_sensor
variables:
  motion_sensor: !input motion_sensor
  target_light: !input target_light
  light_timer: !input light_timer
  motion_enabled: !input motion_enabled
  anchors:
  - &timer_start
    alias: Start timer hoe lang licht nog aan moet blijven
    action: timer.start
    entity_id: !input light_timer
  - &timer_cancel
    alias: Stop timer
    action: timer.cancel
    entity_id: !input light_timer
  - &condition_motion_enabled
    alias: Bewegingsdetectie is ingeschakeld
    condition: state
    entity_id: !input motion_enabled
    state: 'on'
  - &condition_motion_disabled
    alias: Bewegingsdetectie is uitgeschakeld
    condition: state
    entity_id: !input motion_enabled
    state: 'off'
  - &condition_occupancy_on
    alias: Er is beweging gedetecteerd
    condition: state
    entity_id: !input motion_sensor
    state: 'on'
  - &condition_occupancy_off
    alias: Er is geen beweging meer
    condition: state
    entity_id: !input motion_sensor
    state: 'off'
  - &condition_light_on
    alias: Het licht is aan
    condition: state
    entity_id: !input target_light
    state: 'on'
  - &condition_light_off
    alias: Het licht is uit
    condition: state
    entity_id: !input target_light
    state: 'off'
action:
- choose:
  - alias: Stop timer als licht of motion (handmatig) uitgeschakeld is
    conditions:
      or:
      - *condition_light_off
      - *condition_motion_disabled
    sequence:
    - *timer_cancel
  - alias: Stop timer als licht aan is en motion (handmatig) uitgeschakeld is
    conditions:
    - *condition_light_on
    - *condition_motion_disabled
    sequence:
    - *timer_cancel
  - alias: Start timer als geen beweging meer is
    conditions:
    - *condition_motion_enabled
    - *condition_occupancy_off
    sequence:
    - *timer_start
  - alias: Start timer als er opnieuw beweging is
    conditions:
    - *condition_motion_enabled
    - *condition_light_on
    - *condition_occupancy_on
    sequence:
    - *timer_start
  default:
  - *timer_cancel
